name: vae_dct
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - numpy
  - scipy
  - pandas
  - notebook
  - matplotlib
  - wandb
  - scikit-learn
  - tqdm
  - imageio
  - pip
  - wheel
  - pytorch=1.12.1 # 1.11.0
  - torchvision=0.13.1 #10.2
  - cudatoolkit=11.3
  - torchmetrics=0.10.0 # 0.7.1
  - pip:
      - ml-collections==0.1.0
      - hydra-core==1.2
      - torch-fidelity
      - mpi4py
