---
defaults:
  - decoder: ladder
  - encoder: ladder

_target_: model.vae.LADDER_VAE
name: ladder
likelihood: bernoulli
num_mix: 1
beta_start: 1
beta_end: 1
warmup: 0
is_k: 500
free_bits_thr: 0  # https://arxiv.org/pdf/1606.04934.pdf strategy to deal with the KL collease
latent_scales:
  - 0 # 0 latents with dim x//2
  - 2 # 2 latent with dim x//4
latent_width:
  - 0 # 0 channels for the latents of group 1
  - 1 # 1 channel for the latent of group 2
activation: silu  # silu, relu, gelu, elu
batch_norm: True
weight_norm: True
num_ch: 64
scale_ch_mult: 2
block_ch_mult: 0.25
start_scale_at_x: False



