---
data_module:
  _target_: datasets.color_mnist.ColorMNIST
  batch_size: 64
  test_batch_size: 1024
  model: ${model.name}
  ctx_size: null
  mode: RGB
image_size:
  - 3
  - 28
  - 28
n_classes:
  - 10
  - 7
name: color_mnist