---
data_module:
  _target_: datasets.mnists.MNIST
  batch_size: 64
  test_batch_size: 1024
  model: ${model.name}
  ctx_size: null
  mode: BW
image_size:
  - 1
  - 28
  - 28
n_classes:
  - 10
name: mnist